-- -----------------------------------------------------
-- RETO: Calistenia Nivel 0
-- -----------------------------------------------------
DELETE FROM public.reto_dias WHERE reto_id = '3af61f36-dfce-4b79-8689-efb1b133db07';

INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 1, 'Empuje', '"1. Flexiones en pared/mesa: Apoyo alto, control del empuje.\n2. Rotaciones de brazos: Movilidad articular.\n3. Plancha en mesa: Cuerpo recto.\n4. Toques de hombro: De pie o apoyado, tocar hombro opuesto."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 2, 'Piernas', '"1. Sentadillas asistidas silla: Levántate y siéntate sin impulso.\n2. Marcha alta: Rodillas arriba.\n3. Elevación talones: Apoyado en pared.\n4. Pasos laterales: Ritmo constante."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 3, 'Core', '"1. Puente de glúteo: Boca arriba, eleva cadera.\n2. Plancha en rodillas: Mete el ombligo.\n3. Bicho muerto: Boca arriba, alternar toque de pie al suelo.\n4. Toques de talón: Crunch lateral."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 4, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 5, 'Tirón', '"1. Remo c/ toalla: Tensión isométrica.\n2. Superman suave: Elevación leve de pecho.\n3. Retracción escapular: Junta omóplatos.\n4. Plancha invertida rodillas: Eleva cadera sentado."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 6, 'Full / HIIT', '"1. Marcha rápida.\n2. Sentadilla a silla.\n3. Flexiones en pared.\n4. Jumping jacks sin salto (pasos)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 7, 'Empuje', '"1. Flexiones en pared/mesa: Apoyo alto, control del empuje.\n2. Rotaciones de brazos: Movilidad articular.\n3. Plancha en mesa: Cuerpo recto.\n4. Toques de hombro: De pie o apoyado, tocar hombro opuesto."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 8, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 9, 'Piernas', '"1. Sentadillas asistidas silla: Levántate y siéntate sin impulso.\n2. Marcha alta: Rodillas arriba.\n3. Elevación talones: Apoyado en pared.\n4. Pasos laterales: Ritmo constante."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 10, 'Core', '"1. Puente de glúteo: Boca arriba, eleva cadera.\n2. Plancha en rodillas: Mete el ombligo.\n3. Bicho muerto: Boca arriba, alternar toque de pie al suelo.\n4. Toques de talón: Crunch lateral."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 11, 'Tirón', '"1. Remo c/ toalla: Tensión isométrica.\n2. Superman suave: Elevación leve de pecho.\n3. Retracción escapular: Junta omóplatos.\n4. Plancha invertida rodillas: Eleva cadera sentado."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 12, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 13, 'Full / HIIT', '"1. Marcha rápida.\n2. Sentadilla a silla.\n3. Flexiones en pared.\n4. Jumping jacks sin salto (pasos)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 14, 'Empuje', '"1. Flexiones en pared/mesa: Apoyo alto, control del empuje.\n2. Rotaciones de brazos: Movilidad articular.\n3. Plancha en mesa: Cuerpo recto.\n4. Toques de hombro: De pie o apoyado, tocar hombro opuesto."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 15, 'Piernas', '"1. Sentadillas asistidas silla: Levántate y siéntate sin impulso.\n2. Marcha alta: Rodillas arriba.\n3. Elevación talones: Apoyado en pared.\n4. Pasos laterales: Ritmo constante."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 16, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 17, 'Core', '"1. Puente de glúteo: Boca arriba, eleva cadera.\n2. Plancha en rodillas: Mete el ombligo.\n3. Bicho muerto: Boca arriba, alternar toque de pie al suelo.\n4. Toques de talón: Crunch lateral."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 18, 'Tirón', '"1. Remo c/ toalla: Tensión isométrica.\n2. Superman suave: Elevación leve de pecho.\n3. Retracción escapular: Junta omóplatos.\n4. Plancha invertida rodillas: Eleva cadera sentado."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 19, 'Full / HIIT', '"1. Marcha rápida.\n2. Sentadilla a silla.\n3. Flexiones en pared.\n4. Jumping jacks sin salto (pasos)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 20, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('3af61f36-dfce-4b79-8689-efb1b133db07', 21, 'Empuje', '"1. Flexiones en pared/mesa: Apoyo alto, control del empuje.\n2. Rotaciones de brazos: Movilidad articular.\n3. Plancha en mesa: Cuerpo recto.\n4. Toques de hombro: De pie o apoyado, tocar hombro opuesto."');


-- -----------------------------------------------------
-- RETO: Calistenia Nivel 1
-- -----------------------------------------------------
DELETE FROM public.reto_dias WHERE reto_id = '6b6e611f-31e3-4985-a549-4cf7f356b91f';

INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 1, 'Empuje', '"1. Flexiones regulares: Pecho a 2cm del suelo.\n2. Fondos: Baja cadera flexionando codos a 90°.\n3. Plancha c/ toques: Evita balancear la cadera.\n4. Flexiones diamante: Tríceps al fallo."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 2, 'Piernas', '"1. Sentadillas libres: Rompe el paralelo.\n2. Zancadas alternas: Rodilla casi toca el suelo.\n3. Sentadilla isométrica: Espalda a pared, 90°.\n4. Elevaciones talones: Lentas y controladas."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 3, 'Core', '"1. Plancha abdominal: Tensión total.\n2. Hollow body hold: Zona lumbar pegada al suelo.\n3. Escaladores: Velocidad máxima.\n4. Elevación de piernas: Control abdominal."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 4, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 5, 'Tirón', '"1. Dominadas o Remo invertido: Pecho a la barra.\n2. Superman: Junta talones al subir.\n3. Plancha inversa: Cuerpo en línea recta.\n4. Remo isométrico toalla."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 6, 'Full / HIIT', '"1. Burpees: Pecho al piso.\n2. Sentadillas con salto.\n3. Flexiones dinámicas.\n4. Jumping Jacks."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 7, 'Empuje', '"1. Flexiones regulares: Pecho a 2cm del suelo.\n2. Fondos: Baja cadera flexionando codos a 90°.\n3. Plancha c/ toques: Evita balancear la cadera.\n4. Flexiones diamante: Tríceps al fallo."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 8, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 9, 'Piernas', '"1. Sentadillas libres: Rompe el paralelo.\n2. Zancadas alternas: Rodilla casi toca el suelo.\n3. Sentadilla isométrica: Espalda a pared, 90°.\n4. Elevaciones talones: Lentas y controladas."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 10, 'Core', '"1. Plancha abdominal: Tensión total.\n2. Hollow body hold: Zona lumbar pegada al suelo.\n3. Escaladores: Velocidad máxima.\n4. Elevación de piernas: Control abdominal."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 11, 'Tirón', '"1. Dominadas o Remo invertido: Pecho a la barra.\n2. Superman: Junta talones al subir.\n3. Plancha inversa: Cuerpo en línea recta.\n4. Remo isométrico toalla."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 12, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 13, 'Full / HIIT', '"1. Burpees: Pecho al piso.\n2. Sentadillas con salto.\n3. Flexiones dinámicas.\n4. Jumping Jacks."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 14, 'Empuje', '"1. Flexiones regulares: Pecho a 2cm del suelo.\n2. Fondos: Baja cadera flexionando codos a 90°.\n3. Plancha c/ toques: Evita balancear la cadera.\n4. Flexiones diamante: Tríceps al fallo."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 15, 'Piernas', '"1. Sentadillas libres: Rompe el paralelo.\n2. Zancadas alternas: Rodilla casi toca el suelo.\n3. Sentadilla isométrica: Espalda a pared, 90°.\n4. Elevaciones talones: Lentas y controladas."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 16, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 17, 'Core', '"1. Plancha abdominal: Tensión total.\n2. Hollow body hold: Zona lumbar pegada al suelo.\n3. Escaladores: Velocidad máxima.\n4. Elevación de piernas: Control abdominal."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 18, 'Tirón', '"1. Dominadas o Remo invertido: Pecho a la barra.\n2. Superman: Junta talones al subir.\n3. Plancha inversa: Cuerpo en línea recta.\n4. Remo isométrico toalla."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 19, 'Full / HIIT', '"1. Burpees: Pecho al piso.\n2. Sentadillas con salto.\n3. Flexiones dinámicas.\n4. Jumping Jacks."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 20, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('6b6e611f-31e3-4985-a549-4cf7f356b91f', 21, 'Empuje', '"1. Flexiones regulares: Pecho a 2cm del suelo.\n2. Fondos: Baja cadera flexionando codos a 90°.\n3. Plancha c/ toques: Evita balancear la cadera.\n4. Flexiones diamante: Tríceps al fallo."');


-- -----------------------------------------------------
-- RETO: Gym Nivel 0
-- -----------------------------------------------------
DELETE FROM public.reto_dias WHERE reto_id = 'db8f4da2-ff41-45db-898b-951ff4c3242d';

INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 1, 'Empuje', '"1. Press de Pecho (Máquina): Espalda pegada al asiento, empuje fluido.\n2. Press Militar (Mancuernas ligeras): Sentado, no arquees la espalda.\n3. Extensión Tríceps (Polea): Codos fijos a las costillas.\n4. Elevaciones Laterales (Mancuernas): Hasta la altura del hombro."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 2, 'Piernas', '"1. Prensa de Piernas: Pies centrados, baja hasta 90°.\n2. Extensión Cuádriceps (Máquina): Sostén un segundo arriba.\n3. Curl de Isquios (Máquina): Acostado o sentado, movimiento controlado.\n4. Elevación Talones (Sentado en máquina)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 3, 'Core', '"1. Plancha en suelo: Apoyo antebrazos.\n2. Crunch en Máquina o Polea alta.\n3. Elevación Piernas (Silla Romana): Apoya antebrazos y sube rodillas.\n4. Rotación de Torso (Máquina)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 4, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 5, 'Tirón', '"1. Jalón al Pecho (Polea): Barra a la clavícula.\n2. Remo Sentado (Máquina): Jala al ombligo.\n3. Curl de Bíceps (Polea/Mancuerna): Aislamiento.\n4. Face Pull (Polea): Jala hacia los ojos separando codos."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 6, 'Full / HIIT', '"1. 5 min Caminadora (Inclinación moderada).\n2. 5 min Elíptica (Ritmo base).\n3. 5 min Remo Ergómetro.\n4. 5 min Bici estática."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 7, 'Empuje', '"1. Press de Pecho (Máquina): Espalda pegada al asiento, empuje fluido.\n2. Press Militar (Mancuernas ligeras): Sentado, no arquees la espalda.\n3. Extensión Tríceps (Polea): Codos fijos a las costillas.\n4. Elevaciones Laterales (Mancuernas): Hasta la altura del hombro."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 8, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 9, 'Piernas', '"1. Prensa de Piernas: Pies centrados, baja hasta 90°.\n2. Extensión Cuádriceps (Máquina): Sostén un segundo arriba.\n3. Curl de Isquios (Máquina): Acostado o sentado, movimiento controlado.\n4. Elevación Talones (Sentado en máquina)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 10, 'Core', '"1. Plancha en suelo: Apoyo antebrazos.\n2. Crunch en Máquina o Polea alta.\n3. Elevación Piernas (Silla Romana): Apoya antebrazos y sube rodillas.\n4. Rotación de Torso (Máquina)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 11, 'Tirón', '"1. Jalón al Pecho (Polea): Barra a la clavícula.\n2. Remo Sentado (Máquina): Jala al ombligo.\n3. Curl de Bíceps (Polea/Mancuerna): Aislamiento.\n4. Face Pull (Polea): Jala hacia los ojos separando codos."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 12, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 13, 'Full / HIIT', '"1. 5 min Caminadora (Inclinación moderada).\n2. 5 min Elíptica (Ritmo base).\n3. 5 min Remo Ergómetro.\n4. 5 min Bici estática."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 14, 'Empuje', '"1. Press de Pecho (Máquina): Espalda pegada al asiento, empuje fluido.\n2. Press Militar (Mancuernas ligeras): Sentado, no arquees la espalda.\n3. Extensión Tríceps (Polea): Codos fijos a las costillas.\n4. Elevaciones Laterales (Mancuernas): Hasta la altura del hombro."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 15, 'Piernas', '"1. Prensa de Piernas: Pies centrados, baja hasta 90°.\n2. Extensión Cuádriceps (Máquina): Sostén un segundo arriba.\n3. Curl de Isquios (Máquina): Acostado o sentado, movimiento controlado.\n4. Elevación Talones (Sentado en máquina)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 16, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 17, 'Core', '"1. Plancha en suelo: Apoyo antebrazos.\n2. Crunch en Máquina o Polea alta.\n3. Elevación Piernas (Silla Romana): Apoya antebrazos y sube rodillas.\n4. Rotación de Torso (Máquina)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 18, 'Tirón', '"1. Jalón al Pecho (Polea): Barra a la clavícula.\n2. Remo Sentado (Máquina): Jala al ombligo.\n3. Curl de Bíceps (Polea/Mancuerna): Aislamiento.\n4. Face Pull (Polea): Jala hacia los ojos separando codos."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 19, 'Full / HIIT', '"1. 5 min Caminadora (Inclinación moderada).\n2. 5 min Elíptica (Ritmo base).\n3. 5 min Remo Ergómetro.\n4. 5 min Bici estática."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 20, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('db8f4da2-ff41-45db-898b-951ff4c3242d', 21, 'Empuje', '"1. Press de Pecho (Máquina): Espalda pegada al asiento, empuje fluido.\n2. Press Militar (Mancuernas ligeras): Sentado, no arquees la espalda.\n3. Extensión Tríceps (Polea): Codos fijos a las costillas.\n4. Elevaciones Laterales (Mancuernas): Hasta la altura del hombro."');


-- -----------------------------------------------------
-- RETO: Gym Nivel 1
-- -----------------------------------------------------
DELETE FROM public.reto_dias WHERE reto_id = 'b4a23b9e-da61-4956-a389-348d73b9bb06';

INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 1, 'Empuje', '"1. Press de Banca (Barra): Retracción escapular, empuje explosivo.\n2. Press Militar (Barra o Mancuernas): Bloqueo arriba.\n3. Fondos en Máquina o Paralelas del gym.\n4. Cruces en Polea: Contracción máxima en el pecho."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 2, 'Piernas', '"1. Sentadilla con Barra: Controla el descenso, rompe paralelo.\n2. Peso Muerto Rumano (Mancuernas o Barra): Flexión de cadera, tensión en isquios.\n3. Zancadas con Mancuernas: Caminando o estáticas.\n4. Prensa a 1 pierna (Unilateral)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 3, 'Core', '"1. Plancha Lastrada (Disco en espalda).\n2. Ab Wheel (Rueda abdominal): Descenso controlado.\n3. Rodillas al pecho colgado en barra.\n4. Crunch en Polea Alta pesado."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 4, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 5, 'Tirón', '"1. Dominadas o Jalón al pecho pesado.\n2. Remo con Barra: Inclinación 45°.\n3. Curl Bíceps (Barra Z).\n4. Pájaros (Hombro Posterior en banco inclinado)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 6, 'Full / HIIT', '"1. Clean & Press c/ Mancuernas.\n2. Kettlebell Swings.\n3. Burpees saltando al cajón.\n4. Sprints en Remo Ergómetro."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 7, 'Empuje', '"1. Press de Banca (Barra): Retracción escapular, empuje explosivo.\n2. Press Militar (Barra o Mancuernas): Bloqueo arriba.\n3. Fondos en Máquina o Paralelas del gym.\n4. Cruces en Polea: Contracción máxima en el pecho."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 8, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 9, 'Piernas', '"1. Sentadilla con Barra: Controla el descenso, rompe paralelo.\n2. Peso Muerto Rumano (Mancuernas o Barra): Flexión de cadera, tensión en isquios.\n3. Zancadas con Mancuernas: Caminando o estáticas.\n4. Prensa a 1 pierna (Unilateral)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 10, 'Core', '"1. Plancha Lastrada (Disco en espalda).\n2. Ab Wheel (Rueda abdominal): Descenso controlado.\n3. Rodillas al pecho colgado en barra.\n4. Crunch en Polea Alta pesado."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 11, 'Tirón', '"1. Dominadas o Jalón al pecho pesado.\n2. Remo con Barra: Inclinación 45°.\n3. Curl Bíceps (Barra Z).\n4. Pájaros (Hombro Posterior en banco inclinado)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 12, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 13, 'Full / HIIT', '"1. Clean & Press c/ Mancuernas.\n2. Kettlebell Swings.\n3. Burpees saltando al cajón.\n4. Sprints en Remo Ergómetro."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 14, 'Empuje', '"1. Press de Banca (Barra): Retracción escapular, empuje explosivo.\n2. Press Militar (Barra o Mancuernas): Bloqueo arriba.\n3. Fondos en Máquina o Paralelas del gym.\n4. Cruces en Polea: Contracción máxima en el pecho."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 15, 'Piernas', '"1. Sentadilla con Barra: Controla el descenso, rompe paralelo.\n2. Peso Muerto Rumano (Mancuernas o Barra): Flexión de cadera, tensión en isquios.\n3. Zancadas con Mancuernas: Caminando o estáticas.\n4. Prensa a 1 pierna (Unilateral)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 16, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 17, 'Core', '"1. Plancha Lastrada (Disco en espalda).\n2. Ab Wheel (Rueda abdominal): Descenso controlado.\n3. Rodillas al pecho colgado en barra.\n4. Crunch en Polea Alta pesado."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 18, 'Tirón', '"1. Dominadas o Jalón al pecho pesado.\n2. Remo con Barra: Inclinación 45°.\n3. Curl Bíceps (Barra Z).\n4. Pájaros (Hombro Posterior en banco inclinado)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 19, 'Full / HIIT', '"1. Clean & Press c/ Mancuernas.\n2. Kettlebell Swings.\n3. Burpees saltando al cajón.\n4. Sprints en Remo Ergómetro."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 20, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('b4a23b9e-da61-4956-a389-348d73b9bb06', 21, 'Empuje', '"1. Press de Banca (Barra): Retracción escapular, empuje explosivo.\n2. Press Militar (Barra o Mancuernas): Bloqueo arriba.\n3. Fondos en Máquina o Paralelas del gym.\n4. Cruces en Polea: Contracción máxima en el pecho."');


-- -----------------------------------------------------
-- RETO: Híbrido Nivel 0
-- -----------------------------------------------------
DELETE FROM public.reto_dias WHERE reto_id = '99c65247-3076-4f64-a452-4be291946de0';

INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 1, 'Empuje', '"1. Flexiones Inclinadas (En banco de gym).\n2. Press Pecho (Máquina).\n3. Plancha con toques (Suelo).\n4. Extensión Tríceps (Polea)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 2, 'Piernas', '"1. Sentadilla Libre (Cuerpo a cajón/banco).\n2. Prensa de Piernas.\n3. Zancada Asistida o libre sin peso.\n4. Curl Isquios (Máquina)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 3, 'Core', '"1. Puente Glúteo (Suelo).\n2. Plancha Rodillas.\n3. Elevación Piernas (Silla Romana del gym).\n4. Bicho Muerto (Suelo)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 4, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 5, 'Tirón', '"1. Jalón al Pecho (Polea).\n2. Remo Isométrico c/ toalla.\n3. Remo Sentado (Máquina).\n4. Superman (Suelo)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 6, 'Full / HIIT', '"1. Medios Burpees.\n2. Caminadora inclinada (ritmo rápido).\n3. Jumping Jacks.\n4. Bici con resistencia alta."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 7, 'Empuje', '"1. Flexiones Inclinadas (En banco de gym).\n2. Press Pecho (Máquina).\n3. Plancha con toques (Suelo).\n4. Extensión Tríceps (Polea)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 8, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 9, 'Piernas', '"1. Sentadilla Libre (Cuerpo a cajón/banco).\n2. Prensa de Piernas.\n3. Zancada Asistida o libre sin peso.\n4. Curl Isquios (Máquina)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 10, 'Core', '"1. Puente Glúteo (Suelo).\n2. Plancha Rodillas.\n3. Elevación Piernas (Silla Romana del gym).\n4. Bicho Muerto (Suelo)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 11, 'Tirón', '"1. Jalón al Pecho (Polea).\n2. Remo Isométrico c/ toalla.\n3. Remo Sentado (Máquina).\n4. Superman (Suelo)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 12, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 13, 'Full / HIIT', '"1. Medios Burpees.\n2. Caminadora inclinada (ritmo rápido).\n3. Jumping Jacks.\n4. Bici con resistencia alta."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 14, 'Empuje', '"1. Flexiones Inclinadas (En banco de gym).\n2. Press Pecho (Máquina).\n3. Plancha con toques (Suelo).\n4. Extensión Tríceps (Polea)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 15, 'Piernas', '"1. Sentadilla Libre (Cuerpo a cajón/banco).\n2. Prensa de Piernas.\n3. Zancada Asistida o libre sin peso.\n4. Curl Isquios (Máquina)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 16, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 17, 'Core', '"1. Puente Glúteo (Suelo).\n2. Plancha Rodillas.\n3. Elevación Piernas (Silla Romana del gym).\n4. Bicho Muerto (Suelo)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 18, 'Tirón', '"1. Jalón al Pecho (Polea).\n2. Remo Isométrico c/ toalla.\n3. Remo Sentado (Máquina).\n4. Superman (Suelo)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 19, 'Full / HIIT', '"1. Medios Burpees.\n2. Caminadora inclinada (ritmo rápido).\n3. Jumping Jacks.\n4. Bici con resistencia alta."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 20, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('99c65247-3076-4f64-a452-4be291946de0', 21, 'Empuje', '"1. Flexiones Inclinadas (En banco de gym).\n2. Press Pecho (Máquina).\n3. Plancha con toques (Suelo).\n4. Extensión Tríceps (Polea)."');


-- -----------------------------------------------------
-- RETO: Híbrido Nivel 1
-- -----------------------------------------------------
DELETE FROM public.reto_dias WHERE reto_id = '29e4bbc2-7686-4817-bd60-821b45e6a574';

INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 1, 'Empuje', '"1. Fondos en Paralelas (Ideal usar barras altas/robustas de madera para soportar posible lastre).\n2. Press de Banca (Barra pesado).\n3. Flexiones Diamante.\n4. Press Militar (Mancuernas)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 2, 'Piernas', '"1. Sentadilla con Barra pesada.\n2. Zancadas Pliométricas (Saltos).\n3. Peso Muerto Rumano.\n4. Pistol Squat (Asistido en anillas o rack)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 3, 'Core', '"1. L-Sit en Paralelas (Brazos bloqueados).\n2. Ab Wheel (Rueda).\n3. Hollow Rocks.\n4. Plancha Invertida isométrica."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 4, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 5, 'Tirón', '"1. Dominadas Libres (Opción a lastre).\n2. Remo con Barra.\n3. Front Lever Tucks o Remo Invertido en barra baja.\n4. Face Pull (Polea)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 6, 'Full / HIIT', '"1. Burpees c/ flexión estricta.\n2. Thrusters (Mancuernas).\n3. Kettlebell Swings.\n4. Saltos explosivos al cajón."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 7, 'Empuje', '"1. Fondos en Paralelas (Ideal usar barras altas/robustas de madera para soportar posible lastre).\n2. Press de Banca (Barra pesado).\n3. Flexiones Diamante.\n4. Press Militar (Mancuernas)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 8, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 9, 'Piernas', '"1. Sentadilla con Barra pesada.\n2. Zancadas Pliométricas (Saltos).\n3. Peso Muerto Rumano.\n4. Pistol Squat (Asistido en anillas o rack)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 10, 'Core', '"1. L-Sit en Paralelas (Brazos bloqueados).\n2. Ab Wheel (Rueda).\n3. Hollow Rocks.\n4. Plancha Invertida isométrica."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 11, 'Tirón', '"1. Dominadas Libres (Opción a lastre).\n2. Remo con Barra.\n3. Front Lever Tucks o Remo Invertido en barra baja.\n4. Face Pull (Polea)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 12, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 13, 'Full / HIIT', '"1. Burpees c/ flexión estricta.\n2. Thrusters (Mancuernas).\n3. Kettlebell Swings.\n4. Saltos explosivos al cajón."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 14, 'Empuje', '"1. Fondos en Paralelas (Ideal usar barras altas/robustas de madera para soportar posible lastre).\n2. Press de Banca (Barra pesado).\n3. Flexiones Diamante.\n4. Press Militar (Mancuernas)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 15, 'Piernas', '"1. Sentadilla con Barra pesada.\n2. Zancadas Pliométricas (Saltos).\n3. Peso Muerto Rumano.\n4. Pistol Squat (Asistido en anillas o rack)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 16, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 17, 'Core', '"1. L-Sit en Paralelas (Brazos bloqueados).\n2. Ab Wheel (Rueda).\n3. Hollow Rocks.\n4. Plancha Invertida isométrica."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 18, 'Tirón', '"1. Dominadas Libres (Opción a lastre).\n2. Remo con Barra.\n3. Front Lever Tucks o Remo Invertido en barra baja.\n4. Face Pull (Polea)."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 19, 'Full / HIIT', '"1. Burpees c/ flexión estricta.\n2. Thrusters (Mancuernas).\n3. Kettlebell Swings.\n4. Saltos explosivos al cajón."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 20, 'Descanso Activo', '"Misión de hoy: Salir a caminar 30 minutos a paso ligero o hacer 20 minutos de bicicleta. No te exijas, solo mantente en movimiento."');
INSERT INTO public.reto_dias (reto_id, dia_numero, enfoque, rutina_json) VALUES ('29e4bbc2-7686-4817-bd60-821b45e6a574', 21, 'Empuje', '"1. Fondos en Paralelas (Ideal usar barras altas/robustas de madera para soportar posible lastre).\n2. Press de Banca (Barra pesado).\n3. Flexiones Diamante.\n4. Press Militar (Mancuernas)."');


